'use strict'

const esc = require('shell-escape')

module.exports = {
  sh: {
    executor: '/bin/sh',
    generator: ({cmd, args}, binaryPath) => {
      const out = `#!/bin/sh
set -e

# WARNING: THIS FILE IS AUTOGENERATED BY PNEUMON AND WILL GET OVERWRITTEN ANYTIME THE APP IS UPDATED

if [ -e ${esc([binaryPath + '.new'])} ]; then
  mv ${esc([binaryPath + '.new', binaryPath])}
fi
exec ${esc([cmd].concat(args))}`
    }
  }
  // TODO: add bat and ps
}
