'use strict'

const esc = require('shell-escape')

module.exports = {
  sh: {
    executor: '/bin/sh',
    generator: ({cmd, args}, binaryPath) => `#!/bin/sh
set -e

# WARNING: THIS FILE IS AUTOGENERATED BY PNEUMON AND WILL GET OVERWRITTEN ANYTIME THE APP IS UPDATED

if [ -e ${esc([binaryPath + '.new'])} ]; then
  mv ${esc([binaryPath + '.new', binaryPath])}
fi
exec ${esc([cmd].concat(args))}`
  },
  bat: {
    executor: 'C:\\windows\\system32\\cmd.exe',
    generator: ({cmd, args}, binaryPath) => `
@echo off

if exist ${esc([binaryPath + '.new'])} (
    move /Y ${esc([binaryPath + '.new', binaryPath])}
)

${esc([cmd].concat(args))}
`.replace(/\n/g, '\r\n')
  }
  // TODO: add ps
}
